# Set up notification options
notifications:
  email:
    recipients:
      - oliviachenxi@gmail.com

    # change is when the repo status goes from pass to fail or vice versa
    on_success: change
    on_failure: always

# specify language
language: node_js

# specify language options
node_js:
- '6'

# cache the node_modules folder between builds to save time
cache:
  directories:
  - node_modules

## test coverage
install:
  - yarn install

## begin build steps
####################

before_deploy:
- yarn build && ls


## Deployment options
####################

deploy:
  # specify the deployment provider
  provider: firebase
  # options for provider
  token: $FIREBASE_TOKEN
  project: "rectest-8d46f"
  skip_cleanup: true
